name: Java CI with Maven

on:
  push:
    branches:
      [
        "main",
        "test/cristian",
        "test/jonas",
        "hu2-transfers",
        "test/ramaprueba",
      ]
  pull_request:
    branches: ["main", "test/cristian", "test/jonas", "hu2-transfers"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install --file pom.xml

  gatling-account-status:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run AccountStatusTest
        run: mvn gatling:test -Dgatling.simulationClass=AccountStatusTest || true
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-account-status
          path: target/gatling/*

  gatling-billpay:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run BillPay
        run: mvn gatling:test -Dgatling.simulationClass=BillPay || true
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-billpay
          path: target/gatling/*

  gatling-loan-request:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run LoanRequest
        run: mvn gatling:test -Dgatling.simulationClass=LoanRequest || true
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-loan-request
          path: target/gatling/*

  gatling-login-test:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run LoginTest
        run: mvn gatling:test -Dgatling.simulationClass=LoginTest || true
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: gatling-login-test
          path: target/gatling/*
